// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type ClassReq struct {
	Num  string `json:"num"`
	Name string `json:"name"`
	Code string `json:"code"`
}

type ClassPath struct {
	Id int64 `path:"id"`
}

type FindClassReq struct {
	Val      string `form:"val"`      // val
	Page     int    `form:"page"`     // 页数
	PageSize int8   `form:"pageSize"` // 页大小
}

type ClassReply struct {
	Id   int64  `json:"id"`
	Num  string `json:"num"`
	Name string `json:"name"`
	Code string `json:"code"`
}
